# Generated by Django 5.2 on 2025-04-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_remove_user_data_nascimento_remove_user_telefone'),
    ]

    operations = [
    ]
